version: 2
jobs:
  test:
    docker:
      - image: cluelesshamster86/envadmin-build
    steps:
      - checkout
      - run:
          name: Set up pipenv.
          command: pip install pipenv
      - run:
          name: Install dependencies.
          command: pipenv install --dev
      - run:
          name: Install package
          command: pipenv install -e .
      - run:
          name: Create test folder.
          command: mkdir ~/temp && mkdir ~/temp/envadmin_sandbox;
      - run:
          name: Run tests.
          command: export PYTHONPATH=.; pipenv run py.test --reruns 2 --junitxml=pytest/results.xml --cov=envadmin
      - run:
          name: Lint code.
          command: pipenv run pylint envadmin -f parseable >> pylint.log
      - run:
          name: Run mypy
          command: pipenv run mypy envadmin >> mypy.log
      - store_test_results:
          path: pytest
      - store_artifacts:
          path: pylint.log
      - store_artifacts:
          path: mypy.log
      - run:
          name: Send code coverage to Coveralls
          command: pipenv run coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
